language: ruby
rvm:
  - 2.3.0

cache: bundler

services:
  - mysql

env:
  MYSQL_HOST: localhost
  MYSQL_USERNAME: travis
  MYSQL_PASSWORD:
  MYSQL_DATABASE: anrop
  MYSQL_TEST_DATABASE: anrop_test

before_script:
  - bundle exec rails db:setup

script:
  - bundle exec rspec
