# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61d2c5cfb8bc3266902afdb02b31025b29b1439dd378de972a87b9ece167e078fb9e6b5b27ec2e67b3b747999ad1574c21b87dce6bf5048ce6d816d5b9133446

test:
  secret_key_base: a7bc0b4d0735f840d2bac21e80634d20a213e5da26922a929d55a574af46c52040b306fd5de10d811c5171497c597cf2c35fcabdcb21f5af6403504104b03d2a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
